# Configuración de conexión a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/motorcycle_telemetri
spring.datasource.username=root
spring.datasource.password=root

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=telemetrysystem09@gmail.com
spring.mail.password=qcpk ojcm kefy bbsh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true